name: 🚀 Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main # หรือ master ตามชื่อ branch ของคุณ

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Get code from repo
        uses: actions/checkout@v3

      - name: 📤 Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_FOLDER }}
